## This is a first attempt at working with outputList RData files
## generated by H5CellProfiler pipeline
## 18 March 2016 	Wouter den Hollander

## Functions
	getTreatments <- function(x) t(do.call(rbind, lapply(x, function(x) as.character(unique(x$myDT$treatment)))))
	checkReplicates <- function(x, repl = 3) all(table(c(x)) == repl)

	parseOutputList <- function(outputList) {
		.outputList <- outputList
		names(.outputList) <- c('replicate_1', 'replicate_2', 'replicate_3')

		for(i in 1:length(.outputList)) {
			tmp <- .outputList[[i]]

			tmp$myDT$treatment <- gsub('_', '', toupper(gsub(' ', '', tmp$myDT$treatment)))
			
			tmp$sumData$treatment <- gsub('_', '', toupper(gsub(' ', '', tmp$sumData$treatment)))
			tmp$sumData$plateID <- toupper(gsub('_wells', '', tmp$sumData$plateID))
			tmp$sumData$uniqueID <- apply(tmp$sumData, 1, function(x) paste(x[-length(x)], collapse = '_'))
			tmp$sumData$CMAX <- do.call(rbind, strsplit(tmp$sumData$plateID, '_'))[,3]

			tmp$sumData$matchDose <- paste(tmp$sumData$treatment, tmp$sumData$dose_uM, tmp$sumData$CMAX, sep = '_')

			.outputList[[i]] <- tmp
		}

		return(.outputList)
	}	

	getCompoundData <- function(compound, reporter) .dat <- lapply(dat[[reporter]], function(x) x$sumData[x$sumData$treatment == compound, ])

## Settings
	options(stringsAsFactors = FALSE)
	library(data.table)


## Input variables
	inputDir <- '/Users/Wouter/ownCloud/TOX/ExperimentData/DILIscreen/RDataFiles_EndPointDILI/'
	inputFiles <- list.files(inputDir, pattern = '.Rdata')


## Data
	# load 
		for(i in 1:length(inputFiles)) {
			if(!exists('dat')) dat <- list()

			load(paste0(inputDir, inputFiles[[i]]))

			dat[[i]] <- parseOutputList(outputList)
			names(dat)[[i]] <- gsub('outputList', '', gsub('.Rdata', '', inputFiles[[i]]))

			rm(outputList)
			cat(paste0('Loaded ', names(dat)[[i]], '.\n'))
		}	

## Data checks
	# Are the 3 replicates per reporter identical?
		do.call(rbind, lapply(dat, function(y) sapply(y, function(x) nrow(x$sumData))))
		#	      replicate_1 replicate_2 replicate_3
		#	CHOP         3510        3510        3510
		#	ICAM1        2348        2348        2348
		#	P21          3512        3512        3512
		#	SRXN1        3290        3120        3504

	# Are there unexpected dose-xCMAX combinations?

	weirdOnes <- lapply(dat, function(x) {
					.dat <- lapply(x, function(y) data.frame(do.call(rbind, strsplit(y$sumData$matchDose, '_'))))

					for(i in 1:length(.dat)) .dat[[i]]$combined <- paste(.dat[[i]][,1], .dat[[i]][,2], .dat[[i]][,3], sep = '_')
					for(i in 1:length(.dat)) .dat[[i]]$compCMAX <- paste(.dat[[i]][,1], .dat[[i]][,3], sep = '_')

					discrepants <- lapply(.dat, function(y) {
										uniqueDoseCMAX <- data.frame(uniqueCombination = unique(y$compCMAX), disceprany = FALSE)

										for(i in 1:nrow(uniqueDoseCMAX)) {
											.compCMAX <- uniqueDoseCMAX$uniqueCombination[i]
											uniqueDoseCMAX$disceprany[i] <- length(unique(y[which(y$compCMAX == .compCMAX), 'X2'])) > 1
										}

										.y <- y[which(y$compCMAX %in% uniqueDoseCMAX$uniqueCombination[which(uniqueDoseCMAX$disceprany)]), ]
										.y <- .y[order(.y$compCMAX), 1:3]

										.y
									})
					
					discrepants	
				})


	for(i in 1:length(weirdOnes)) {
		tmp <- weirdOnes[[i]]

		for(j in 1:length(tmp)) {
			write.table(tmp[[j]], file = paste0(inputDir, names(weirdOnes)[i], names(tmp)[j], '.txt'), quote = FALSE, sep = '\t')
		}
	} 
















###############################################
################### LEGACY ####################
		# Check treatment-dose combinations in dat
			dsg <- read.delim(paste0(inputDir, 'COMPOUND_DOSE.txt'), dec = ',')
				colnames(dsg)[grep('cmax', colnames(dsg))] <- c('1CMAX', '5CMAX', '10CMAX', '25CMAX', '50CMAX', '100CMAX')
				dsg$treatment <- toupper(gsub(' ', '', dsg$Compound_))

				dsg$treatment[grep('TACROLIMUS', dsg$treatment)] <- 'TACROLIMUS'
				dsg$treatment[grep('ARSENITE', dsg$treatment)] <- 'SODIUMARSENITE'
				dsg$treatment[grep('STAUSPORIN', dsg$treatment)] <- 'STAUROSPORIN'
				dsg$treatment[grep('FOXIMINE', dsg$treatment)] <- 'BUTHIONINESULFOXAMINE'
				dsg$treatment[grep('DMNQ', dsg$treatment)] <- 'DMNQ'

				for(i in grep('CMAX', colnames(dsg))) dsg[ ,i] <- paste(dsg$treatment, dsg[,i], colnames(dsg)[i], sep = '_')
		
	## Checks
		# Are the 3 replicates per reporter identical?
			do.call(rbind, lapply(dat, function(y) sapply(y, function(x) nrow(x$sumData))))
			#			             replicate_1 replicate_2 replicate_3
			#	CHOP                		3512        3512        3615
			#	CHOP_newRun         		3510        3510        3510
			#	ICAM1               		2348        2348        2348
			#	P21                 		3512        3512        3512
			#	SRXN1               		3290        3120        3513
			#	SRXN1_newRun        		3290        3120        3504	


		# Get discrepant dose_xCMAX combinations
			findDiscrepantCombinations <- function(dat) {
				if(.debug) tmp <- dat$SRXN1_newRun
			}	


		# Check SRXN1_newRun discrepancies
			# unqTreatments <- unlist(dsg[,grep('CMAX', colnames(dsg))])
			# toCheckAgainst <- dat$SRXN1_newRun$replicate_3$sumData$matchDose

			# SRXN1_newRUn
			tmp <- names(which(table(unlist(sapply(dat$SRXN1_newRun, function(x) x$sumData$matchDose))) != 9))
			.tmp <- apply(do.call(rbind, strsplit(tmp, '_'))[,c(1,3)], 1, function(x) paste0(x, collapse = '_'))
			data.frame(tmp[duplicated(.tmp)])

			# P21 issues
			tmp <- names(which(table(unlist(sapply(dat$P21, function(x) x$sumData$matchDose))) != 9))
			.tmp <- apply(do.call(rbind, strsplit(tmp, '_'))[,c(1,3)], 1, function(x) paste0(x, collapse = '_'))
			data.frame(tmp[duplicated(.tmp)])

			# CHOP_newRUn
			tmp <- names(which(table(unlist(sapply(dat$CHOP_newRun, function(x) x$sumData$matchDose))) != 9))
			.tmp <- apply(do.call(rbind, strsplit(tmp, '_'))[,c(1,3)], 1, function(x) paste0(x, collapse = '_'))
			data.frame(tmp[duplicated(.tmp)])

			# ICAM1
			tmp <- names(which(table(unlist(sapply(dat$ICAM1, function(x) x$sumData$matchDose))) != 9))
			.tmp <- apply(do.call(rbind, strsplit(tmp, '_'))[,c(1,3)], 1, function(x) paste0(x, collapse = '_'))
			data.frame(tmp[duplicated(.tmp)])


		# Which conditions are not present in all replicates per compound
			datConditionReplicates <- lapply(dat, function(x) table(unlist(lapply(x, function(y) y$sumData$matchDose ))))
			missingMeasurements <- lapply(datConditionReplicates, function(x) x[x < 9])
			




		# Explore CHOP discrepancies (replicate 3 platelayout contains errors) 
			rep1 <- dat$CHOP$replicate_1$sumData[grep('1CMAX', dat$CHOP$replicate_1$sumData$plateID), ]
			rep3 <- dat$CHOP$replicate_3$sumData[grep('1CMAX', dat$CHOP$replicate_3$sumData$plateID), ]

			rep1_1cmax <- apply(cbind(rep1$treatment, t(sapply(strsplit(rep1$plateID, '_'), function(x) x[c(1,3)]))), 1, function(x) paste(x, collapse = '_'))
			rep3_1cmax <- apply(cbind(rep3$treatment, t(sapply(strsplit(rep3$plateID, '_'), function(x) x[c(1,3)]))), 1, function(x) paste(x, collapse = '_'))
			
			rep1[grep('TUNICAMYCIN_C_24H_1CMAX', rep1_1cmax), ]
			rep3[grep('TUNICAMYCIN_C_24H_1CMAX', rep3_1cmax), ]

		# Explore SRXN1 discrepancies
			tmp <- dat$SRXN1
			tmpTreatments <- lapply(tmp, function(x) do.call(rbind, strsplit(x$sumData$uniqueID, '_REP'))[,1])
				
			example1 <- 'TACROLIMUS'
			example2 <- 'KANAMYCIN'	

		
			lapply(dat, function(y) lapply(y, function(x) x$sumData$treatment[!x$sumData$treatment %in% dsg$treatment]))
			# All experiments contain treatments with compounds present in comound list

			lapply(dat, function(y) lapply(y, function(x) dsg$treatment[!dsg$treatment %in% x$sumData$treatment]))
			# None of the experiments contain CYTOCHALASIND and PHENACETIN		!

			unqTreatments <- unique(dsg$treatment)

			checkTreatmentDoseComb <- function(dsgEntry, replicateSumData) {
				# dsgEntry <- dsg[1,]
				# replicateSumData <- CHOP$replicate_1$sumData
				# cat(colnames(dsgEntry))
				dosesPresent <- sapply(grep('CMAX', colnames(dsgEntry)), function(i) dsgEntry[,i] %in% replicateSumData$matchDose )
					if(all(dosesPresent)) {
						return(data.frame(treatment = dsgEntry$treatment, found = TRUE))
					} else {
						return(data.frame(treatment = dsgEntry$treatment, found = FALSE))
					}
					
			}

			cmaxMatched <- do.call(rbind, lapply(1:nrow(dsg), function(x) checkTreatmentDoseComb(dsg[x,], dat$SRXN1_newRun$replicate_3$sumData)))

			getDiscrepancies <- function(treatment, replicateSumData) {
				# treatment <- 'VERAPAMIL'
				# treatment <- 'FLUOXETINE'

				treatmentInd <- which(replicateSumData$treatment == treatment)
				
				tmpData <- replicateSumData$matchDose[treatmentInd]
				tmpDsg <-  unlist(dsg[which(dsg$treatment == treatment), grep('CMAX', colnames(dsg))])

				presentInDsgNotInData <- tmpData[!tmpData %in% tmpDsg]
				presentInDataNotInDsg <- tmpDsg[!tmpDsg %in% tmpData]

				return(list(presentInCompoundListNotInData = presentInDsgNotInData, presentInDataNotInCompoundList = presentInDataNotInDsg))
			}

			nonMatchedTreatments <- cmaxMatched$treatment[!cmaxMatched$found]
			Discrepancies <- lapply(nonMatchedTreatments, function(x) getDiscrepancies(x, dat$SRXN1_newRun$replicate_3$sumData))



		# Compound overview
			comp <- read.delim(paste0(inputDir, 'COMPOUNDS.txt'))		# list of compounds
			
			# parse
			comp <- comp[rowSums(is.na(comp)) != (ncol(comp)-1), ]		# remove empty rows 
			comp$COMPOUND <- toupper(gsub(' ', '', comp$COMPOUND))


	## Explore data
		# Are the 3 replicates per reporter identical?
			do.call(rbind, lapply(dat, function(y) sapply(y, function(x) nrow(x$sumData))))
			#			             replicate_1 replicate_2 replicate_3
			#	CHOP                		3512        3512        3615
			#	CHOP_newRun         		3512        3512        3510
			#	ICAM1               		2348        2348        2348
			#	P21                 		3512        3512        3512
			#	SRXN1               		3290        3120        3513
			#	SRXN1_newRun        		3290        3120        3504	

		# Which treatments are non-identical across replicates?
			treatmentLists <- lapply(dat, function(y) sapply(y, function(x) x$sumData$uniqueID))

			treatmentsCHOP <- lapply(sapply(treatmentLists$CHOP, function(x) do.call(rbind, strsplit(x, '_REP'))), function(x) x[,1])
			treatmentsCHOP_newRun <- lapply(sapply(treatmentLists$CHOP_newRun, function(x) do.call(rbind, strsplit(x, '_REP'))), function(x) x[,1])
			
			treatmentsSRXN1_newRun <- lapply(sapply(treatmentLists$CHOP_newRun, function(x) do.call(rbind, strsplit(x, '_REP'))), function(x) x[,1])
			

			treatmentsICAM1 <- lapply(sapply(treatmentLists$ICAM1, function(x) do.call(rbind, strsplit(x, '_REP'))), function(x) x[,1])
			treatmentsP21 <- lapply(sapply(treatmentLists$P21, function(x) do.call(rbind, strsplit(x, '_REP'))), function(x) x[,1])
			treatmentsSRXN1 <- lapply(sapply(treatmentLists$SRXN1, function(x) do.call(rbind, strsplit(x, '_REP'))), function(x) x[,1])


		# Are there any duplicate 'unique' treatments?
			lapply(dat, function(y) sapply(y, function(x) names(which(table(x$sumData$uniqueID) != 1))))
			# DMEM 'treatment' is not unqiue (DMEM possibly not necessary) 				!






















		# Do all replicates per dataset contain the same compounds?
			treatments <- lapply(dat, getTreatments)
			sapply(treatments, checkReplicates)
			#	CHOP ICAM1   P21 SRXN1 
		 	#	TRUE  TRUE  TRUE  TRUE 

	 	# Do all datasets contain the same compounds?
		 	all(table(c(sapply(treatments, function(x) x[,1]))) == 4)
			#	[1] TRUE

		# Screen compounds in list of compounds? 
			unqTreatments <- names(table(c(sapply(treatments, function(x) x[,1]))))
			unqCompounds <- comp$COMPOUND

			unqTreatments[!unqTreatments %in% unqCompounds]
			#	[1] "DEM_C"         "DMEM"          "DMNQ"          "DMSO"         
			#	[5] "ETOPOSIDE_C"   "TUNICAMYCIN_C"
			#	ETOPOSIDE_C & TUNICAMYCIN_C are 'duplicates' of non_C treatments

		# Are all compounds have thesame dose range over time for all replicates?
			doseRanges <- lapply(1:3, function(i) { do.call(rbind, lapply(unqTreatments, function(x) {
								sapply(dat, function(y) {
										tmp <- y[[1]]$sumData
										ind <- which(tmp$treatment == x)
										nrow(tmp[ind,])
									})
								}))	
							})
				for(i in 1:length(doseRanges)) rownames(doseRanges[[i]]) <- unqTreatments


			
	## Test whether DILI compounds are significantly different from DMSO on sumData
		testDiff <- function(compound, reporter, concentration, timepoint) {
			compound <- 'DICLOFENAC'
			reporter <- 'SRXN1'
			concentration <- '100CMAX'
			timepoint <- '48'

			#.dat <- do.call(rbind, lapply(getCompoundData(compound, reporter), function(x) x[x$timeID == timepoint & grepl(concentration, x$plateID),]))
			#.dmso <- do.call(rbind, lapply(getCompoundData('DMSO', reporter), function(x) x[x$timeID == timepoint & grepl(concentration, x$plateID),]))
			# which dose to take for DMSO?	
			.dat <- do.call(rbind, lapply(getCompoundData(compound, reporter), function(x) x[grepl(concentration, x$plateID),]))
			.dmso <- do.call(rbind, lapply(getCompoundData('DMSO', reporter), function(x) x[grepl(concentration, x$plateID),]))
			.dmem <- do.call(rbind, lapply(getCompoundData('DMEM', reporter), function(x) x[grepl(concentration, x$plateID),]))
		}

	## Clustering (not dose/timepoint specific)













